var R=require("./chunks/[turbopack]_runtime.js")("server/instrumentation.js")
R.c("server/chunks/[externals]_node:inspector_dc347386._.js")
R.c("server/chunks/474fd_@sentry_core_build_cjs_7a9adefd._.js")
R.c("server/chunks/474fd_@opentelemetry_api_build_esm_4ba30c53._.js")
R.c("server/chunks/474fd_@opentelemetry_core_build_esm_89da079b._.js")
R.c("server/chunks/474fd_@opentelemetry_16e21d0a._.js")
R.c("server/chunks/474fd_@sentry_node-core_build_cjs_3ef1525e._.js")
R.c("server/chunks/474fd_@opentelemetry_sdk-trace-base_build_esm_0e650cfe._.js")
R.c("server/chunks/474fd_@opentelemetry_resources_build_esm_d1943c1c._.js")
R.c("server/chunks/474fd_@sentry_node_build_cjs_9aa6a9f7._.js")
R.c("server/chunks/474fd_@sentry_nextjs_build_cjs_5e396fcd._.js")
R.c("server/chunks/474fd_a7ff7905._.js")
R.c("server/chunks/[root-of-the-server]__f396e97a._.js")
R.m("[project]/Documents/zama/merces-front2/src/instrumentation.ts [instrumentation] (ecmascript)")
module.exports=R.m("[project]/Documents/zama/merces-front2/src/instrumentation.ts [instrumentation] (ecmascript)").exports
