var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__c5522e7a._.js")
R.c("server/chunks/ssr/Documents_zama_merces-front2_10525028._.js")
R.c("server/chunks/ssr/Documents_zama_merces-front2_d9969ac4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e878bef8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e990fa7._.js")
R.c("server/chunks/ssr/474fd_48b0635f._.js")
R.c("server/chunks/ssr/Documents_zama_merces-front2_src_app_2f0fa50f._.js")
R.c("server/chunks/ssr/Documents_zama_merces-front2_src_app_global-error_tsx_df21a096._.js")
R.c("server/chunks/ssr/474fd_next_dist_2a769705._.js")
R.c("server/chunks/ssr/474fd_next_290643d4._.js")
R.c("server/chunks/ssr/Documents_zama_merces-front2_02ebf7cb._.js")
R.c("server/chunks/ssr/Documents_zama_merces-front2_src_app_not-found_tsx_66e2194e._.js")
R.c("server/chunks/ssr/474fd_next_dist_client_components_b53f4cc3._.js")
R.c("server/chunks/ssr/474fd_next_dist_client_components_builtin_unauthorized_a8214a5c.js")
R.c("server/chunks/ssr/Documents_zama_merces-front2__next-internal_server_app_page_actions_d4a023ca.js")
R.m(10078)
module.exports=R.m(10078).exports
