var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0d5f5d1d._.js")
R.c("server/chunks/ssr/Documents_zama_merces-front2_10525028._.js")
R.c("server/chunks/ssr/474fd_next_dist_ca0c24f2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e4e0224d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e990fa7._.js")
R.c("server/chunks/ssr/474fd_48b0635f._.js")
R.c("server/chunks/ssr/Documents_zama_merces-front2_src_app_2f0fa50f._.js")
R.c("server/chunks/ssr/e7a81_merces-front2__next-internal_server_app__global-error_page_actions_089fa480.js")
R.m(96868)
module.exports=R.m(96868).exports
